name: CI pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build and Test (Go ${{ matrix.go-version }})

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.17", "1.18"]
  
    steps:
    - uses: actions/checkout@v3
    
    - name: Start localstack
      run: docker-compose up -d
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.46.0
        args: -c .golangci.yml --timeout 5m

    - name: Build SAM
      run: make build

    - name: Generate Zip Deployment
      run: make zip-deployment

    - name: Launch tests
      run: make test
    - name: Stop containers
      if: always()
      run: docker-compose down      
