name: CI pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build and Test (Go ${{ matrix.go-version }})

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.17", "1.18"]
    env:
      ENVIRONMENT: ci
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
      DEFAULT_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1  
  
    steps:
    - uses: actions/checkout@v3
    
    - name: Start localstack
      run: docker-compose up -d
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Download tools
      run: make download-tools
    
    - name: Run linter
      run: make lint

    - name: Build SAM
      run: make build

    - name: Generate Zip Deployment
      run: make zip-deployment

    - name: Launch tests
      run: make test
    - name: Stop containers
      if: always()
      run: docker-compose down      
